language: generic

jobs:
  include:
    - stage: 
      name: "Tasks for push event"
      if: (type = push OR type = pull_request) AND tag =~ ^(?!veracode-).*
      script:
        - echo "This is push event 12"
    - stage:
      name: "Tasks for cron event"
      if: type = cron OR tag =~ ^(veracode-).*
      script:
        - echo "This is cron or veracode tag event"
