language: generic

if: type = push
  before_install:
    - echo "This is push test"
    - ls -la
    - rm -rf folder1
    - ls -la

if: type = cron
  before_install:
    - echo "This is cron test"
    - ls -la
    - rm -rf folder2
    - ls -la