language: generic

jobs:
  include:
    - stage: 
      name: "Tasks for push event"
      if: type = push OR type = pull
      before_script:
        - uname -a
      script:
        - echo "This is push event"
        - java -version
      deploy:
        - provider: script
          script: ./lets_deploy.sh
    - stage:
      name: "Tasks for cron event"
      if: type = cron
      env: BUILDTYPE="cron"
      script:
        - echo "This is cron event"
        - java -version
        - ls -la
    

script:
  - echo $BUILDTYPE