language: generic

jobs:
  include:
    - stage: 
      name: "Assign push var"
      if: type = push
      env: BUILDTYPE="push"
    - stage:
      name: "Assign cron var"
      if: type = cron
      env: BUILDTYPE="cron"
    

script:
  - echo $BUILDTYPE