language: generic

env:
  - VERACODEWRAPPERVERSION: "20.3.6.1"

jobs:
  include:
    - stage: 
      name: "Tasks for push event"
      if: type = push OR type = pull_request
      before_script:
        - uname -a
        - wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/20.3.6.1/vosp-api-wrappers-java-$VERACODEWRAPPERVERSION.jar
      script:
        - echo "This is push event"
        - java -version
        - java -jar vosp-api-wrappers-java-$VERACODEWRAPPERVERSION.jar -help
      #deploy:
      #  - provider: script
      #    script: ./lets_deploy.sh
    - stage:
      name: "Tasks for cron event"
      if: type = cron
      env: BUILDTYPE="cron"
      script:
        - echo "This is cron event"
        - java -version
        - ls -la
